import { GuestCompendium, UpsellService } from "./types"

export const UPSELL_SERVICES: UpsellService[] = [
  {
    id: "late-checkout-2pm",
    title: "Late Check-Out (Until 14:00 WIB)",
    category: "timing",
    description: "Nikmati waktu istirahat lebih lama. Check-out diperpanjang hingga pukul 14:00 (tergantung ketersediaan jadwal pembersihan).",
    priceIdr: 150000,
    unit: "per booking",
    icon: "Clock",
    popular: true,
  },
  {
    id: "late-checkout-4pm",
    title: "Late Check-Out Super Extended (Until 16:00 WIB)",
    category: "timing",
    description: "Santai tanpa terburu-buru sampai sore hari pukul 16:00 WIB.",
    priceIdr: 250000,
    unit: "per booking",
    icon: "Sunset",
  },
  {
    id: "bbq-grill-set",
    title: "BBQ Charcoal Grill Set + Arang & Torch",
    category: "experience",
    description: "Perangkat panggangan BBQ lengkap dengan arang briket kelapa 3kg, fire starter, capitan stainless, dan meja outdoor.",
    priceIdr: 200000,
    unit: "per malam",
    icon: "Flame",
    popular: true,
    applicableSlugs: ["versatile-house-jagakarsa"],
  },
  {
    id: "extra-bed-hotel",
    title: "Extra Bed Single + Hotel Linen & Bantal",
    category: "comfort",
    description: "Kasur busa rebonded hotel standard (90x200cm) lengkap dengan sprei katun 300TC, selimut duvet tebal, dan 2 bantal empuk.",
    priceIdr: 150000,
    unit: "per malam",
    icon: "BedDouble",
  },
  {
    id: "mid-stay-refresh",
    title: "Mid-Stay Housekeeping & Linen Replacement",
    category: "housekeeping",
    description: "Pembersihan total lantai, penggantian handuk baru, perapihan kasur, pembersihan kamar mandi, dan buang sampah.",
    priceIdr: 175000,
    unit: "per kunjungan",
    icon: "Sparkles",
  },
  {
    id: "floating-breakfast-tray",
    title: "Floating Breakfast Basket Setup",
    category: "experience",
    description: "Keranjang anyam floating tray estetik tahan air untuk foto sarapan cantik di kolam renang privat.",
    priceIdr: 100000,
    unit: "per sewa",
    icon: "Coffee",
    applicableSlugs: ["versatile-house-jagakarsa"],
  },
  {
    id: "early-checkin-late-checkout-versatile",
    title: "Early Check-In / Late Check-Out (Versatile House)",
    category: "timing",
    description: "Penyesuaian jadwal check-in lebih awal (sebelum 15:00) atau check-out lebih lama (setelah 12:00) khusus villa Versatile House Jagakarsa.",
    priceIdr: 950000,
    unit: "per request",
    icon: "Clock",
    applicableSlugs: ["versatile-house-jagakarsa"],
  },
]

export const GUEST_COMPENDIUMS: Record<string, GuestCompendium> = {
  "versatile-house-jagakarsa": {
    propertySlug: "versatile-house-jagakarsa",
    propertyName: "Versatile House With Beautiful Garden Beyond",
    area: "Jagakarsa, Jakarta Selatan",
    heroImage: "/properties/versatile-house/VersatileHouse_Exterior_PoolAndGarden.webp",
    whatsappConciergePhone: "6282123933218",
    wifi: {
      networkName: "VersatileHouse_Guest_5G",
      password: "KingHouseGarden2026",
      speed: "100 Mbps Fiber Biznet",
      notes: "Router utama berada di ruang keluarga dekat TV. Hubungkan ke frekuensi 5GHz untuk streaming lancar.",
    },
    access: {
      checkInTime: "15:00 WIB (Flexible)",
      checkOutTime: "Sebelum 12:00 WIB (12:00 PM)",
      smartLockCodeOrPin: "Pin diberikan 2 jam sebelum kedatangan oleh host via Airbnb / WhatsApp",
      accessInstructions: [
        "Pintu gerbang utama dilengkapi smart lock digital keypad.",
        "Masukkan 6-digit PIN yang telah dikirimkan via WA lalu akhiri dengan tanda '#'.",
        "Kunci cadangan dan remote AC master tersedia di keyholder dinding ruang tamu.",
        "Early Check-in / Late Check-out dikenakan biaya Rp 950.000 (tergantung ketersediaan jadwal).",
      ],
      parkingInfo: "Garasi & carport dalam muat hingga 4 mobil keluarga. Parkir aman dengan pagar tertutup.",
    },
    houseRules: [
      "1. Pets: Pets are not allowed. Service animals are accommodated as required by Airbnb policy.",
      "2. Events: Events are not allowed for standard overnight stays (Price & package for events is separate from overnight stays).",
      "3. Smoking: Smoking, vaping, and e-cigarettes are not allowed indoors. Smoking is allowed outdoors only (gazebo & garden area).",
      "4. Quiet Hours: 10:00 PM – 6:00 AM. Please keep noise levels down and respect the neighbors.",
      "5. Commercial Photography & Filming: Commercial photography and filming are not allowed. Photo/video and film shooting for events is also disallowed without prior booking/permission.",
      "6. Maximum Overnight Guests: Maximum 12 guests for overnight stays. Each bedroom is designed for 2 guests.",
      "7. Check-in & Check-out: Check-in: 3:00 PM – Flexible | Check-out: before 12:00 PM (Early Check-in / Late Check-out: Rp950,000).",
      "8. Additional Charges: Extra charge Rp300,000 for each guest after 4 guests. Cleaning fee: Rp350,000.",
      "9. Additional Policies: Property surveys or site visits are not permitted prior to booking.",
      "10. Communication Policy: For security and documentation purposes, all inquiries and communication must be conducted through the Airbnb messaging system.",
    ],
    appliances: [
      {
        title: "Smart TV & Netflix / Disney+ Hotstar",
        icon: "Tv",
        instructions: [
          "Nyalakan TV dengan remote hitam Samsung.",
          "Profil 'Guest KingHouse' sudah login otomatis untuk Netflix & YouTube Premium 4K.",
        ],
      },
      {
        title: "Water Heater & Kamar Mandi Utama",
        icon: "Droplet",
        instructions: [
          "Saklar water heater Ariston menyala otomatis 24 jam.",
          "Putar tuas shower ke arah kiri (merah) untuk air hangat. Tunggu 10 detik.",
        ],
      },
      {
        title: "Dapur & Kompor Tanam Gas",
        icon: "Flame",
        instructions: [
          "Tekan kenop kompor ke dalam, putar ke kiri berlawanan arah jarum jam sambil menahan pemantik elektrik 3 detik.",
          "Air mineral galon dispenser Aqua sudah terpasang (panas & dingin).",
        ],
      },
    ],
    localGuide: [
      {
        name: "Kopi Nako Jagakarsa",
        category: "Food & Cafe",
        distance: "1.2 km (5 menit)",
        highlight: "Cafe kaca estetik dengan live music & menu kopi susu aren terbaik.",
        mapsUrl: "https://maps.google.com/?q=Kopi+Nako+Jagakarsa",
      },
      {
        name: "Bebek Kaleyo Lenteng Agung",
        category: "Food & Cafe",
        distance: "2.5 km (8 menit)",
        highlight: "Kuliner bebek goreng kremes & sambal rica legendaris keluarga.",
        mapsUrl: "https://maps.google.com/?q=Bebek+Kaleyo+Lenteng+Agung",
      },
      {
        name: "Indomaret Fresh Moh. Kahfi 1",
        category: "Convenience & Grocery",
        distance: "400 meter (Jalan kaki 3 menit)",
        highlight: "Buka 24 jam, buah segar, ATM BCA/Mandiri, dan kebutuhan sehari-hari.",
        mapsUrl: "https://maps.google.com/?q=Indomaret+Fresh+Moh+Kahfi+1",
      },
      {
        name: "RSUD Jagakarsa & Apotek Kimia Farma",
        category: "Emergency & Pharmacy",
        distance: "1.8 km (6 menit)",
        highlight: "IGD 24 jam dan apotek resep obat lengkap.",
        mapsUrl: "https://maps.google.com/?q=RSUD+Jagakarsa",
      },
    ],
  },

  "sky-house-tangerang": {
    propertySlug: "sky-house-tangerang",
    propertyName: "Sky House • Hotel-Style Bed + IKEA 5min",
    area: "Pinang, Kota Tangerang (Alam Sutera)",
    heroImage: "/properties/sky-house/SkyHouse_LivingArea_BedView.webp",
    whatsappConciergePhone: "6282123933218",
    wifi: {
      networkName: "KINGSKYHOUSE22",
      password: "120210120069#",
      speed: "50 Mbps Fiber",
      notes: "High-speed connection for remote work, streaming, and video calls.",
    },
    access: {
      checkInTime: "15:00 WIB",
      checkOutTime: "12:00 PM (12:00 WIB)",
      smartLockCodeOrPin: "Akses kartu tap lift & Smart Lock Door handle",
      accessInstructions: [
        "Ambil kartu akses di security lobby Ground Floor.",
        "Tap kartu di lift menuju lantai unit.",
        "Buka pintu unit dengan memasukkan PIN di handle pintu digital.",
        "Check-out: Matikan seluruh utilitas/listrik, tinggalkan kartu akses & kunci di atas meja, dan pastikan pintu & jendela terkunci rapat.",
      ],
      parkingInfo: "Parkir basement apartemen tarif normal per jam atau hubungi pengelola untuk voucher harian.",
    },
    houseRules: [
      "NO SMOKING — Strictly no smoking inside the room or indoor area.",
      "NO PETS ALLOWED — Pets are not permitted in the unit.",
      "PLEASE FLUSH THE TOILET AFTER USE — Keep bathroom clean and sanitary.",
      "PLEASE SWITCH OFF ALL THE ELECTRICITY POINTS WHEN NOT IN USE — Turn off AC, lights, and appliances when leaving.",
      "PLEASE KEEP THE ROOM CLEAN, TIDY, AND HYGIENIC — Treat the space with care.",
      "PLEASE DO NOT MAKE ANY NOISE POLLUTION — Respect quiet hours and neighboring residents.",
      "PLEASE KEEP THE ITEMS BACK AFTER USAGE — Return appliances and utensils to original place.",
      "ANY MATERIAL DAMAGE BY THE GUEST WILL BE CHARGED — Guests are responsible for replacement/repair costs.",
      "PLEASE DO NOT EAT OR DRINK ON THE BED — Any stains on the bedding will be subject to a cleaning fee.",
      "CHECK-OUT GUIDELINES: Check-out time 12:00 PM • Turn off utilities • Leave access card & key on the table • Make sure doors & windows are properly locked.",
      "IF YOU ENJOYED YOUR STAY, PLEASE LEAVE US A REVIEW ⭐",
    ],
    appliances: [
      {
        title: "AC Inverter Daikin",
        icon: "Wind",
        instructions: [
          "Gunakan remote AC dinding. Suhu ideal hemat energi 22-24°C.",
          "Matikan AC saat meninggalkan ruangan demi efisiensi energi.",
        ],
      },
      {
        title: "Microwave & Kulkas Mini",
        icon: "Utensils",
        instructions: [
          "Microwave siap pakai untuk memanaskan makanan cepat saji atau takeaway.",
        ],
      },
    ],
    localGuide: [
      {
        name: "IKEA Alam Sutera & Flavor Bliss",
        category: "Food & Cafe",
        distance: "1.5 km (5 menit)",
        highlight: "Swedish meatballs, bakery, dan pusat kuliner hits Tangerang.",
        mapsUrl: "https://maps.google.com/?q=IKEA+Alam+Sutera",
      },
      {
        name: "Mall @ Alam Sutera",
        category: "Attraction",
        distance: "2.0 km (7 menit)",
        highlight: "Bioskop XXI, supermarket Aeon, dan puluhan restoran.",
        mapsUrl: "https://maps.google.com/?q=Mall+Alam+Sutera",
      },
      {
        name: "Apotek Century & FamilyMart Lobby",
        category: "Convenience & Grocery",
        distance: "Lantai GF Apartemen",
        highlight: "Buka 24 jam untuk kopi fresh dan obat-obatan ringan.",
        mapsUrl: "https://maps.google.com/?q=Sky+House+Alam+Sutera",
      },
    ],
  },

  "bright-airy-apartment-palmerah": {
    propertySlug: "bright-airy-apartment-palmerah",
    propertyName: "Bright & Airy Apartment",
    area: "Palmerah, Jakarta Barat",
    heroImage: "/properties/bright-airy-palmerah/BrightAiry_Living_Sofa_TV.jpg",
    whatsappConciergePhone: "6282123933218",
    wifi: {
      networkName: "BrightPalmerah_Fast",
      password: "PalmerahStay2026",
      speed: "50 Mbps",
      notes: "Dedicated fiber router di dekat meja kerja.",
    },
    access: {
      checkInTime: "15:00 WIB",
      checkOutTime: "12:00 WIB",
      smartLockCodeOrPin: "Keybox di samping pintu unit",
      accessInstructions: [
        "Keybox terletak di sebelah kanan bel pintu.",
        "Masukkan kode PIN 4 digit untuk membuka kotak kunci.",
        "Buang sampah pada ruang shaft sampah yang tersedia di dekat lorong lift.",
      ],
      parkingInfo: "Parkir tersedia di area gedung apartemen.",
    },
    houseRules: [
      "No smoking inside the unit (Dilarang merokok di dalam kamar/unit).",
      "No pets allowed (Dilarang membawa hewan peliharaan).",
      "Dilarang mengadakan pesta atau mengundang tamu luar berlebihan.",
      "Jagalah kebersihan dapur dan buang sampah di ruang shaft lantai.",
      "Quiet hours: Harap menjaga ketenangan setelah pukul 22:00 WIB.",
    ],
    appliances: [
      {
        title: "Smart TV & High-Speed WiFi",
        icon: "Tv",
        instructions: ["Smart TV dengan aplikasi YouTube dan Netflix siap nonton."],
      },
    ],
    localGuide: [
      {
        name: "Senayan City & Plaza Senayan",
        category: "Attraction",
        distance: "3.5 km (10 menit)",
        highlight: "Pusat perbelanjaan luxury, fine dining, dan bioskop bioskop.",
        mapsUrl: "https://maps.google.com/?q=Senayan+City",
      },
      {
        name: "Stasiun KRL Palmerah",
        category: "Attraction",
        distance: "1.0 km (4 menit)",
        highlight: "Akses cepat KRL Tanah Abang & Serpong.",
        mapsUrl: "https://maps.google.com/?q=Stasiun+Palmerah",
      },
    ],
  },

  "skyline-luxury-orange-county-cikarang": {
    propertySlug: "skyline-luxury-orange-county-cikarang",
    propertyName: "Skyline Luxury at Orange County",
    area: "Cikarang Selatan, Bekasi",
    heroImage: "/properties/skyline-luxury-orange-county-cikarang/SkylineLuxury_Living_Sofa_Balcony.jpg",
    whatsappConciergePhone: "6282123933218",
    wifi: {
      networkName: "N0510",
      password: "Kinghouse",
      speed: "100 Mbps Dedicated Fiber",
      notes: "Kecepatan ultra-cepat ideal untuk corporate expat & business stay.",
    },
    access: {
      checkInTime: "15:00 WIB",
      checkOutTime: "12:00 WIB",
      smartLockCodeOrPin: "Self check-in via Mailbox N0510 (Newport Building)",
      accessInstructions: [
        "Welcome to Skyline Luxury at Orange County ✨",
        "Self check-in: Head to Newport Building and ask security to show you the mailbox area.",
        "Look for mailbox N0510 to retrieve your room key and access card.",
        "The room is located on the 5th floor (Unit N0510).",
        "Delivery: You can pick up packages at security in front of the lobby (Orange County – Unit N0510).",
        "Facilities: Pool, gym, playground on Level 2 (Access card required).",
        "Trash: Dispose of garbage in the KWH room (nearby the lift).",
      ],
      parkingInfo: "Dedicated lot parkir tamu di B1 (Access card required).",
    },
    houseRules: [
      "No smoking 🚭 (Strictly prohibited inside the unit).",
      "No pets allowed.",
      "No parties or commercial use.",
      "Do not rearrange the furniture.",
      "Please keep the noise down and respect the neighbors 🙏.",
      "ELECTRICAL SAFETY SUGGESTION: For safety reasons and to prevent electrical overload, please do not use high-power appliances such as the electric stove, hair dryer, and electric kettle at the same time. We kindly ask that you use them one at a time to ensure a stable power supply and a comfortable stay.",
      "TRASH DISPOSAL: Dispose of garbage in the KWH room (nearby the lift).",
      "DELIVERY SERVICE: Package deliveries can be picked up at security in front of the lobby (Unit N0510).",
    ],
    appliances: [
      {
        title: "Electrical Appliances & Power Usage",
        icon: "Flame",
        instructions: [
          "Untuk keselamatan dan mencegah kelebihan beban listrik (overload), mohon tidak menggunakan peralatan berdaya tinggi seperti kompor listrik, hair dryer, dan ketel listrik secara bersamaan.",
          "Gunakan peralatan listrik berdaya tinggi satu per satu (one at a time) demi kestabilan daya dan kenyamanan stay Anda.",
        ],
      },
      {
        title: "Washing Machine & Dryer",
        icon: "Sparkles",
        instructions: ["Mesin cuci front loading otomatis lengkap dengan deterjen gel."],
      },
      {
        title: "Modern Kitchenette & Induction Stove",
        icon: "Utensils",
        instructions: ["Kompor induksi dan peralatan masak premium. Bersihkan setelah penggunaan."],
      },
    ],
    localGuide: [
      {
        name: "Citywalk Lippo Cikarang & Japanese Dining",
        category: "Food & Cafe",
        distance: "1.5 km (5 menit)",
        highlight: "Authentic Izakaya, Ramen, dan supermarket Papaya Fresh Gallery.",
        mapsUrl: "https://maps.google.com/?q=Citywalk+Lippo+Cikarang",
      },
      {
        name: "Mall Lippo Cikarang",
        category: "Attraction",
        distance: "3.0 km (8 menit)",
        highlight: "Pusat belanja, bioskop, dan kuliner keluarga.",
        mapsUrl: "https://maps.google.com/?q=Mall+Lippo+Cikarang",
      },
    ],
  },
}
