import { Reservation, ExpenseRecord } from "./types"
import { calculateReservationPayout } from "./calculations"

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: "RES-8921",
    propertyId: "villa-1",
    propertySlug: "versatile-house-jagakarsa",
    propertyName: "Versatile House With Beautiful Garden Beyond",
    guestName: "Hartono & Family",
    guestPhone: "+62 812-3456-7890",
    guestEmail: "hartono.family@gmail.com",
    channel: "Airbnb",
    checkIn: "2026-08-22",
    checkOut: "2026-08-25",
    nights: 3,
    guests: 10,
    grossPayoutIdr: 5400000,
    cleaningFeeIdr: 300000,
    feeTier: "standard",
    managementFeePercent: 15,
    managementFeeIdr: 765000,
    netOwnerPayoutIdr: 4335000,
    status: "Confirmed",
    notes: "Family staycation + backyard BBQ request",
    createdAt: "2026-08-18T10:30:00Z",
  },
  {
    id: "RES-8922",
    propertyId: "villa-3",
    propertySlug: "bright-airy-apartment-palmerah",
    propertyName: "Bright & Airy Apartment Near Slipi",
    guestName: "Adrian Kowalski",
    guestPhone: "+48 501-234-567",
    guestEmail: "adrian.k@techcorp.pl",
    channel: "Airbnb",
    checkIn: "2026-08-23",
    checkOut: "2026-08-28",
    nights: 5,
    guests: 2,
    grossPayoutIdr: 1750000,
    cleaningFeeIdr: 100000,
    feeTier: "standard",
    managementFeePercent: 15,
    managementFeeIdr: 247500,
    netOwnerPayoutIdr: 1402500,
    status: "Active Stay",
    notes: "Expat remote worker - high-speed WiFi required",
    createdAt: "2026-08-20T14:15:00Z",
  },
  {
    id: "RES-8923",
    propertyId: "villa-4",
    propertySlug: "skyline-luxury-orange-county-cikarang",
    propertyName: "Skyline Luxury at Orange County Cikarang",
    guestName: "Kenji Sato",
    guestPhone: "+81 90-1234-5678",
    guestEmail: "kenji.sato@toyota-supplier.co.jp",
    channel: "Direct WhatsApp",
    checkIn: "2026-08-24",
    checkOut: "2026-08-31",
    nights: 7,
    guests: 2,
    grossPayoutIdr: 4550000,
    cleaningFeeIdr: 150000,
    feeTier: "premium",
    managementFeePercent: 20,
    managementFeeIdr: 880000,
    netOwnerPayoutIdr: 3520000,
    status: "Checked-in Ready",
    notes: "Engineering consultant direct corporate billing",
    createdAt: "2026-08-21T09:00:00Z",
  },
  {
    id: "RES-8924",
    propertyId: "villa-2",
    propertySlug: "sky-house-serpong-tangerang",
    propertyName: "Sky House • Hotel-Style Bed + IKEA 5min",
    guestName: "Nadia Putri",
    guestPhone: "+62 813-8899-7766",
    guestEmail: "nadia.putri@gmail.com",
    channel: "Airbnb",
    checkIn: "2026-08-29",
    checkOut: "2026-08-31",
    nights: 2,
    guests: 2,
    grossPayoutIdr: 840000,
    cleaningFeeIdr: 80000,
    feeTier: "standard",
    managementFeePercent: 15,
    managementFeeIdr: 114000,
    netOwnerPayoutIdr: 646000,
    status: "Confirmed",
    notes: "Weekend transit near Alam Sutera / ICE BSD",
    createdAt: "2026-08-22T16:45:00Z",
  },
]

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: "EXP-101",
    propertyId: "villa-1",
    propertySlug: "versatile-house-jagakarsa",
    propertyName: "Versatile House With Beautiful Garden Beyond",
    category: "PLN & Utilities",
    description: "Token Listrik PLN Pascabayar (5.500 VA)",
    amountIdr: 650000,
    date: "2026-08-05",
    recordedBy: "Budi (Ops Jagakarsa)",
    vendorName: "PLN UID Jakarta Raya",
  },
  {
    id: "EXP-102",
    propertyId: "villa-1",
    propertySlug: "versatile-house-jagakarsa",
    propertyName: "Versatile House With Beautiful Garden Beyond",
    category: "Linen & Laundry",
    description: "Cuci Bed Sheet King Size + Quilt Cover 5BR (20kg Express)",
    amountIdr: 280000,
    date: "2026-08-12",
    recordedBy: "Siti (Housekeeping)",
    vendorName: "AquaClean Laundry Jagakarsa",
  },
  {
    id: "EXP-103",
    propertyId: "villa-4",
    propertySlug: "skyline-luxury-orange-county-cikarang",
    propertyName: "Skyline Luxury at Orange County Cikarang",
    category: "Guest Amenities",
    description: "Restock Kopi Nespresso, Teh Artisan, Galon Aqua & Toiletries Kit",
    amountIdr: 185000,
    date: "2026-08-15",
    recordedBy: "Rian (Ops Cikarang)",
    vendorName: "Papaya Fresh Gallery",
  },
  {
    id: "EXP-104",
    propertyId: "villa-2",
    propertySlug: "sky-house-serpong-tangerang",
    propertyName: "Sky House • Hotel-Style Bed + IKEA 5min",
    category: "Maintenance & Repairs",
    description: "Cuci AC Split Inverter 1PK + Isi Freon R32",
    amountIdr: 150000,
    date: "2026-08-18",
    recordedBy: "Doni (Technician)",
    vendorName: "Sejuk Jaya AC Serpong",
  },
]
